# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.name: '%env(APP_NAME)%'
    app.admin_email: '%env(ADMIN_EMAIL)%'
    
    # directorio para la subida de ficheros por defecto
    app.uploads: '%kernel.project_dir%/uploads'
    
    # directorio para la subida de imagen de portada de un lugar( relativa y absoluta)
    app.covers: '%env(APP_COVERS)%'
    app.covers.root: '%kernel.project_dir%/public/%app.covers%'
    
    # directorio para la subida de retratos de actors( relativa y absoluta)
    app.portraits: '%env(APP_PORTRAITS)%'
    app.portraits.root: '%kernel.project_dir%/public/%app.portraits%'
    
    # directorio para la subida de imágenes de lugares ( relativa y absoluta)
    app.pictures: '%env(APP_PICTURES)%'
    app.pictures.root: '%kernel.project_dir%/public/%app.pictures%'
    
    # directorio para la subida de fotos de usuario (relativa y absoluta)
    app.users_pics: '/resources/images/users'
    # app.users_pics: 'APP_USERS_PICS'
    app.users_pics_root: '%kernel.project_dir%/%app.users_pics%'
    # número de resultados por página para la paginación
    app.page_results: 3
    app.place_results: 3
    app.photo_results: 12
    app.comment_results: 10
    app.user_results: 6
    
    # conficuraión del número de enlaces del paginador
    # 2 significa 2 por arriba 2 por abajo, por 3ejemplo
    # si estamos en la página 4, aparecen enlaces de la 2 a al 6
    app.paginator_links: 2
    
    # numero de imágenes en la portada de un place
    app.portada.covers: 4

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    App\Service\FileService:
        arguments:
            # $targetDirectory: '%app.covers_root%'
            $targetDirectory: '%app.uploads%'
    
    App\Service\PaginatorService:
        # para el autowiring
        arguments:
            $limit: '%app.page_results%'
